import Head from "next/head";
import { useTheme } from "next-themes";
import { Button } from "@components/Button";
import { Text } from "@components/Text";
import { Heading } from "@components/Heading";
import { Stack } from "@components/Stack";
import { Box } from "@components/Box";
import { Container } from "@components/Container";
import { Link } from "@components/Link";

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <>
      <Head>
        <title>Kenny Elshoff</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Box
        css={{
          width: "$full",
          bg: "$slateA2",
          borderBottom: "1px solid $slateA4",
          py: "$3",
        }}
      >
        <Container
          css={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
          }}
          size="2"
        >
          <Heading size="1" variant="blue" weight="9">
            KE
          </Heading>
          <Button
            size="1"
            variant="blue"
            onClick={() => {
              return theme === "dark" ? setTheme("light") : setTheme("dark");
            }}
          >
            Change theme
          </Button>
        </Container>
      </Box>
      <Container as="main" css={{ py: "$9", minHeight: "100vh" }} size="2">
        <Stack css={{ stackGap: "$7" }}>
          <Stack css={{ stackGap: "$3" }}>
            <Heading as="p" size="2" variant="contrast" weight="9">
              Welcome!
            </Heading>
            <Stack css={{ stackGap: "$4" }}>
              <Text
                css={{ lineHeight: "$relaxed" }}
                size={{
                  "@initial": "3",
                  "@bp2": "4",
                }}
                variant="gray"
              >
                My name is Kenny. I&apos;m a front-end engineer & designer.
                I&apos;m a lover of systems, finding patterns,{" "}
                <Link
                  href="https://unsplash.com/"
                  target="_blank"
                  variant="blue"
                >
                  snowboarding
                </Link>
                , and occasionally{" "}
                <Link
                  href="https://unsplash.com/"
                  target="_blank"
                  variant="blue"
                >
                  photography
                </Link>
              </Text>
              <Text
                css={{ lineHeight: "$relaxed" }}
                size={{
                  "@initial": "3",
                  "@bp2": "4",
                }}
                variant="gray"
              >
                Currently working with{" "}
                <Link
                  href="https://grahammedia.com/"
                  rel="noopener"
                  target="_blank"
                  variant="subtle"
                >
                  Graham Media Group
                </Link>{" "}
                to build Local News better.
              </Text>
            </Stack>
          </Stack>
        </Stack>
      </Container>
    </>
  );
}
